name: Continuous integration

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  execute_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: pip3 install --no-cache-dir -r requirements-dev.txt
      - name: Execute unit tests
        run: pytest tests/test_syspathmodif.py
