name: Continuous integration

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  execute_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up minimal Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Intall the development dependencies
        run: pip3 install --no-cache-dir -r requirements-dev.txt
      - name: Execute the unit tests
        run: pytest tests
  test_demos_no_error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up minimal Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Intall the dependencies
        run: pip3 install --no-cache-dir -r requirements.txt
      - name: Demo 1 - Individual paths
        run: python3 demos/demo1_individual_paths.py
      - name: Demo 2 - SysPathBundle
        run: python3 demos/demo2_bundle.py
      - name: Demo 3 - SysPathBundle as a context manager
        run: python3 demos/demo3_bundle_context.py
      - name: Demo 4 - SysPathBundle's content is None
        run: python3 demos/demo4_bundle_none_empty.py --paths . demo_package
      - name: Demo 5 - sm_contains A
        run: python3 demos/demo5_sm_contains_A.py
      - name: Demo 6 - sm_contains B
        run: python3 demos/demo6_sm_contains_B.py
      - name: Demo 7 - Prepending a parent path
        run: python3 demos/demo7_parent.py
      - name: Demo 8 - Prepending a parent bundle
        run: python3 demos/demo8_parent_bundle.py
  test_bundle_clearing_app_end:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up minimal Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Intall the dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Clear a bundle when an application ends
        run: python .github/workflows/test_bundle_clearing_app_end.py
  test_pypi_package_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up minimal Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Test the build
        run: python3 .github/workflows/test_pypi_package_build.py
