name: Continuous integration

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  execute_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Intall the development dependencies
        run: pip3 install --no-cache-dir -r requirements-dev.txt
      - name: Execute the unit tests
        run: pytest tests
  test_demos_no_error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Intall the dependencies
        run: pip3 install --no-cache-dir -r requirements.txt
      - name: Run the SysPathBundle demo
        run: python3 demos/demo_bundle.py
      - name: Run the SysPathBundle context manager demo
        run: python3 demos/demo_bundle_context.py
      - name: Run the functions' demo
        run: python3 demos/demo_functions.py
      - name: Run the first sm_contains demo
        run: python3 demos/demo_sm_contains1.py
      - name: Run the second sm_contains demo
        run: python3 demos/demo_sm_contains2.py
  test_bundle_clearing_app_end:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Intall the dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Clear a bundle when an application ends
        run: python .github/workflows/test_bundle_clearing_app_end.py
  test_pypi_package_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Test the build
        run: python3 .github/workflows/test_pypi_package_build.py
